DeclareDesign/estimatr

R/clean_model_data.R
R/lm_lin.R
R/lm_robust.R
R/na_omit_detailed.R
man/lm_lin.Rd
man/lm_robust.Rd

@lukesonnet This is the refactor I had mentioned in #33 - instead of manually removing NA in extra components (weight, cluster, ...) one at a time, we can have `model.frame` do it. I also tried to limit the NSE to one frame of the call stack at a time, so this ended up being a bit larger diff than I usually like.
All the package tests still pass and I've verified there isn't a performance hit, but I'd appreciate any feedback if there's something I overlooked.

Refactor: clean_model_data and na.omit to track why obs are omitted

---

R/RcppExports.R
R/lm_lin.R
R/lm_robust.R
R/lm_robust_fit.R
R/tidy.R
README.Rmd
README.md
man/lm_lin.Rd
man/lm_robust.Rd
man/lm_robust_fit.Rd
src/RcppExports.cpp
src/lm_robust_helper.cpp

Changes a warning message with rank-deficient X, renames the argument `trychol`, and replaces a link in the readme to be absolute rather than relative so it works on both declaredesign.org and github.
Will merge once I check on the automated checks (and if they finally work in a PR, then I'll close issues #50 and #51).

Minor Edits

---

R/lm_robust_fit.R
R/tidy.R

This closes issue #72 by adding column names to user supplied `X` if they are missing and adding `output` to the list returned by `lm_robust_fit`.
Furthermore, because we actually add the `lm_robust` class to the output of `lm_robust_fit` and not later, users can just use `tidy()` on the return of `lm_robust_fit`. This is the object hierarchy muddiness @nfultz is talking about.
So we can leave it as is, merge it in, and close #72, or we can add the class later, and instruct users they have to use `estimatr:::tidy.lm_robust()` if they want to tidy `lm_robust_fit`.

Allows output of lm_robust_fit to be tidied

---

R/lm_lin.R
tests/testthat/test-lm-lin.R

This fixes a bug where if you ran
```
lm_lin(y ~ x, ~ factor(block), data = dat)
```
the usage of `all.vars` would mean we would build the full formula of `y ~ x + block` instead of `y ~ x + factor(block)`.
Using labels on terms solves this as it keeps all of the terms rather than just the variables from the `covariates = ` argument.

Fixed lm_lin bug dropping functions of covariates

---

src/lm_robust_helper.cpp
tests/testthat/test-lm-cluster.R

If last cluster (numerically) was a singleton, then it was skipped in the estimation of cluster robust variance. This fixes that problem (and as an added benefit simplifies the algorithm).
This should be merged ASAP (lets let atleast AppVeyor check it), I think.

Solve bug with clustered SEs

---

R/estimatr_difference_in_means.R
R/estimatr_lm_lin.R
R/estimatr_lm_robust.R
R/helper_lm_robust_fit.R
man/difference_in_means.Rd
man/lm_lin.Rd
man/lm_robust.Rd
tests/testthat/test-lm-lin.R
vignettes/estimatr.bib
vignettes/getting-started.Rmd
vignettes/technical-notes.Rmd

This PR is working on style, man pages, error language, and coverage. Starting with lm_robust, lm_lin, and working it's way through the other estimators and functions.

Man page for `lm_robust`

---

cran-comments.md

There isn't a tarball in itself, but can you check this and check the .Rbuildignore looks right for that? Once you do that, I'll devtools::release()

Add cran comments

---

docs/articles/getting-started.html
docs/articles/technical-notes.html
vignettes/getting-started.Rmd
vignettes/technical-notes.Rmd

Fixed the math in the vignettes; refs still broken.
Tried to emulate these refs here(https://cran.rstudio.com/web/packages/ggmcmc/vignettes/using_ggmcmc.html) using the YAML and bib set up they use, but to no avail.

Fix Vignettes

---

DESCRIPTION
R/estimatr_lm_lin.R
tests/testthat/test-lm-lin.R
vignettes/getting-started.Rmd
vignettes/technical-notes.Rmd

Changes "_bar" variable suffix to "_c" for centered pre-treatment covariates.
Makes according changes in tests and in vignette.
Also demonstrates leeper/prediction usage in getting started.

Fix lin variable name; closes #121

---

src/lm_robust_helper.cpp
tests/testthat/test-lm-lin.R
tests/testthat/test-lm-robust_margins.R

There were some "deep" CRAN errors we needed to resolve that you can see here: https://cran.r-project.org/web/checks/check_results_estimatr.html
1. Tests failed without Long Doubles (https://www.stats.ox.ac.uk/pub/bdr/noLD/estimatr.out). They were not identical but rather equal, so I just changed the test.
2. Uninitialized values (the degrees of freedom, residuals, and residual variance in `lm_robust_helper.cpp` were being used and returned to the R wrapper code and were causing errors in Valgrind. I now initialize these values and tested all of the test files one by one using valgrind and there are no more errors.
3. Solaris errored on a test that `expect_equal` the max diff of two `margins` was less than < 2e05. I changed the test to `expect_equals` with a tolerance of 0.01. I have no …

Make tweaks for CRAN

---

.travis.yml
src/lm_robust_helper.cpp
tests/testthat/test-lm-cluster.R

Fixes meat of CR2 variance estimator when there are weights.
Adds tests, clubSandwich to travis for tests.
This should be merged ASAP.

Fix transposed hat messing up weighted CR2 variance

---

R/estimatr_difference_in_means.R
R/estimatr_lm_lin.R
tests/testthat/test-difference-in-means.R
tests/testthat/test-lm-lin.R

Previously, `lm_lin` was not demeaning covariates by the weighted mean, and was just using the simple mean (Issue #148). This has been solved.
After solving it, a test failed checking `difference_in_means` against `lm_lin` in the blocked, weighted case. This test previously passed because both were wrong in the same say!
The above problem is solved now. In `difference_in_means()` we compute the post-stratification estimator as:
```r
diff <- with(block_estimates, sum(coefficients * N / N_overall))
```
The problem was that we used `N` and `N_overall` rather than the sum of the weights in a block and the sum of all of the weights if you had a blocked, weighted specification. Now `N` and `N_overall` appropriately capture the weights.

Fixes weighting for lm_lin and blocked difference_in_means

---

R/S3_summary.R
R/S3_tidy.R
tests/testthat/test-condition1-condition2.R
tests/testthat/test-difference-in-means.R
tests/testthat/test-horvitz-thompson.R
tests/testthat/test-iv-robust.R
tests/testthat/test-lm-cluster.R
tests/testthat/test-lm-robust.R
tests/testthat/test-replicate-HT-middleton.R
tests/testthat/test-replicate-lin2013.R
tests/testthat/test-s3-methods.R

Really weird that the list output doesn't match the tidy output now, but I think matching the tidy output is probably right so that everything is internally consistent.. There are 3 problems with also changing the list output of the estimator functions:
1. `lm` returns an object with `res$coefficients` and if we change our list so that the coefficients are in `robres$estimate`, but `summary(robres)$coefficients` still matches `summary(res)$coefficients`, then we are sometimes matching, sometimes not.
2. We have a (small) set of users who might be thrown off by this (I don't think this is a real big concern as now is the time to make this change if ever).
3. We have to rework DD diagnosands and designs to also be consistent, because otherwise it's still internally inconsistent
I think …

Changes tidy output

---

R/estimatr_difference_in_means.R
R/estimatr_horvitz_thompson.R
R/estimatr_iv_robust.R
R/helper_clean_model_data.R
tests/testthat/test-horvitz-thompson.R

This does two things:
1. Changes `clean_model_data` to take a string for which estimator is calling it so that we can do better handling some things that need to be added to the data. Could break these into separate fns, but I'm not sure that's better.
2. Allows ht to work with a declaration and without data. Before it tried to check things in the declaration against things in the data but the data might not exist and so it was erroring. Now, there is v little chance of internal clash over naming since fultzy prepends `.__251353...` to auxiliary variables. Also, different lengths of variables in the `declaration` and `data` if it is passed is just handled by `model.frame`

Change how ht parses data

---

R/S3_vcov.R
tests/testthat/test-s3-methods.R

Also adds test for new coef (code looks fine to continue relying on `coef.default`.
Closes #204. Can't see any other pertinent S3 changes.

Update vcov for 3.5

---

R/S3_confint.R
R/S3_summary.R
R/S3_tidy.R
R/estimatr_difference_in_means.R
R/estimatr_horvitz_thompson.R
R/estimatr_iv_robust.R
R/estimatr_lm_lin.R
R/estimatr_lm_robust.R
R/helper_cis_pvals.R
R/helper_return.R
R/helper_starprep.R
tests/testthat/test-difference-in-means.R
tests/testthat/test-horvitz-thompson.R
tests/testthat/test-lm-cluster.R
tests/testthat/test-replicate-lin2013.R
tests/testthat/test-return.R
tests/testthat/test-s3-methods.R

I was writing software that makes strong assumptions column names in the output of `broom::tidy`. It broke when I applied it to an `lm_robust` object, because `broom::tidy` uses `ci.low` and `ci.high`, while `estimatr::tidy` uses `ci.lower` and `ci.upper`. 
Since your function seems to have been inspired by `broom`, and since that package is under the popular tidyverse umbrella, I think it makes sense to standardize column names.
This commit just substitutes the names, and fixes the tests accordingly.

estimatr::tidy colnames are compatible with broom:tidy colnames

---

R/helper_clean_model_data.R
R/helper_lm_robust_fit.R
tests/testthat/test-lm-robust-fes.R

Solves Macartan's problem about wanting support for their being a fixed effect with only one group. Note for now we do not support a fixed effect with only one group if there are multiple fixed effect variables.
Also solves a bug where if there is one fixed effect variable and missingness, `clean_model_data` returns a vector rather than a matrix for the fixed effects.

Add support for one group in a fixed effect

---

DESCRIPTION
NEWS.md

All this does is bump up the version for submission. One concern I have is that the versioning is a bit weird. We lose the history of the intermediate versions, which isn't ideal, however, removing them preserves the NEWS.md as a version history for CRAN, which is what most people are going to use.
Not sure what to do. Maybe there should be a secondary NEWS.md that is more complete?

Bump version to 0.12 for CRAN

---

.travis.yml
R/S3_tidy.R
R/zzz.R
tests/testthat/test-zzz.R

This PR will `packageStartupMessage` if `broom` version <= 0.5.0, the current CRAN version, is attached. If they attach broom afterwards, there's no guarantee.
Hopefully the `broom` that relies on `generics` will be on CRAN soon.
This also tests the message is silent if the right version of `broom` is installed and that it messages with the old version. Travis hopefully is set up to test both on Linux, release R.

Add .onLoad warning for old versions of broom

---

R/estimatr_iv_robust.R
R/estimatr_lm_robust.R
man/iv_robust.Rd
man/lm_robust.Rd

Hello :-)
The DOI foundation recommends [this new resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8). It may be a bit ironic that they would change the URL of their service, but it's now [encrypted](https://www.ssllabs.com/ssltest/analyze.html?d=doi.org). Because the old `dx` subdomain is being redirected, there is no urgent need to do anything.
However, I'd hereby like to suggest to follow the new recommendation by applying this update to all static DOI links.
Cheers!

Hyperlink DOIs to preferred resolver

---

.travis.yml
tests/testthat/test-condition-pr-matrix.R
tests/testthat/test-s3-methods.R
tests/testthat/test-starprep.R

- libgit2 needed for mac osx builds
- in R-devel, several test errors
For the latter, the problem comes from seeds generating different random data in R-devel. In two cases, this meant that the test configuration failed for non-serious reasons:
- for the predict test error, the sample data had collinearity and I just needed to increase the size or change the seed
- for the condition_pr_matrix test error, I needed to increase the sample draws of the treatment vector to make sure the condition_pr_mat built using treatment permutations still matches the analytic condition_pr_mat
However, for the fstat error, the new random data revealed that there are still differences between fstats computed via `lm_robust` and `commarobust`. This is due to (computational error) numerical differences …

Fix travis issues

---

DESCRIPTION
NEWS.md
R/estimatr_lm_lin.R
README.Rmd
README.md
tests/testthat/test-lm-lin.R

- Hardcodes readme urls so it works on github and website (closes #273)
- Fixes unnecessary duplication of treatment variable in `lm_lin` (closes #283)

WIP - Prep v0.16 for CRAN

---

DESCRIPTION
NEWS.md
R/estimatr_lm_robust.R
cran-comments.md
man/lm_robust.Rd
tests/testthat/test-iv-robust.R

Respond to CRAN notice to fix errors:
1) Tests fail due to update in clubSandwich **(resolved)**
2) Same segfaults on Solaris in demeanMat, which I have been unable to resolve despite trying to silo the problem and rewriting the code many times **(unresolved)**
Make other small changes:
1) add note about missingness in mlm (closes #299)  **(resolved)**

CRAN patch and other small changes

---

DESCRIPTION
NEWS.md
R/S3_emmeans.R
R/estimatr_lm_robust.R
R/zzz.R
man/lm_robust.Rd
tests/testthat/test-lm-robust_emmeans.R
vignettes/emmeans-examples.Rmd

I have added the code needed to support the **emmeans** package for use with `lm_robust` objects. This provides a nice way (nicer than **margins**, IMHO) to obtain marginal means, etc.
The changes are:
* in `DESCRIPTION`: Add `emmeans` and the needed version
* new file `S3_emmeans.R`: The S3 methods needed by **emmeans**
there is one to recover the dataset, and one that is kind of like the insides of the
`predict` method for new data. 
* in `estimatr_lm_robust.R`: Additions to the documentation
* in `zzz.R`: Register the S3 methods
```r
library(estimatr)
library(emmeans)
warp.rlm <- lm_robust(formula = breaks ~ wool * tension, data = warpbreaks)
emmeans(warp.rlm, ~ tension | wool)
emmip(warp.rlm, wool ~ tension, CIs = TRUE)
```
```r
warpi.rlm <- update(warp.rlm, subset = -(37:48))
(rgi <- …
```

Added emmeans support

---

R/helper_clean_model_data.R

We can just follow their advice and cast `mfargs` to a list, as at a certain point we only ever evaluate elements in `mfargs` within `data`.
Please confirm this handles your warnings. I can't really test for this unless I figure out how to renew a session within a test, or create a test with a name that alphabetically comes first (and thus triggers the one warning per session warning).
Or I guess I could figure out if there's a way to always surface those warnings.
e: I just looked through how `rlang` tests these warnings and they ensure they are not on cran and then actually generate different deprecation warnings. I think we can rely on just checking warnings for now.

Solves rlang 0.4.0 warnings #307

---

tests/testthat/test-starprep.R

Addresses #328 
I think this should work, but it's not guaranteed. I think we should say we tried to address the numerical uncertainty that is causing this in this test. If we still are getting flagged then we may need to try a more brute force approach with weird values in `compute_fstat()`.

change tests to be less likely to fail

---

R/helper_extract.R
tests/testthat/test-texreg.R

While `extract.lm_robust` is gross, it looks like the other extract functions. So until such a time it gets completely re-written, I'm just going to add features as in this PR, where I add the ability to include the number of clusters for clustered designs.

Add n clusters to extract.lm_robust

---

R/helper_starprep.R
tests/testthat/test-starprep.R

Thanks to @notanastronomer for the heads up on this! I've edited her MWE below a bit. 
People often like to carry around lists of lm fits, e.g. using lapply over a list of formulas. Currently, these are not handled by `starprep()`.
```
library(estimatr)
library(stargazer)
a <- lm(mpg ~ cyl, mtcars)
b <- lm(mpg ~ cyl + disp, mtcars)
c <- lm(mpg ~ cyl + disp + hp, mtcars)
abc <- list(a, b, c)
ab <- list(a, b)
starprep(a,b,c)
starprep(abc)
starprep(a,b)
starprep(ab)
```
This behavior worries me a bit, as I can see people doing something like this:
```
stargazer(a, b, se = starprep(ab), type = "text")
```
Expecting to get this:
```
stargazer(a, b, se = starprep(a,b), type = "text")
```
I've written an admittedly very quick and dirty fix in this PR, in case it's helpful to build off.

Starprep list

---

R/helper_clean_model_data.R
tests/testthat/test-arg-checking.R

Early check for formula type, closes #349
Use R 4.0 style labeled stopifnot, but backwards compatible.

Early check for formula type, closes #349

---

DESCRIPTION
NEWS.md
R/S3_tidy.R
R/S3_vcov.R
R/helper_return.R
man/estimatr_glancers.Rd
man/estimatr_tidiers.Rd
tests/testthat/test-s3-methods.R

The `tidy` methods packaged with `broom` and `broom.mixed` include two arguments that are currently unsupported by `estimatr`: `conf.int` and `conf.level`. 
I ran into this problem when using `modelsummary`, a package which extracts information from models using `tidy`. This code produces a regression table and a coefficients plot, but the confidence intervals are incorrect, because `estimatr::tidy` ignores arguments that standard `tidy` methods accept:
```r
library(modelsummary)
library(estimatr)
mod <- lm_robust(mpg ~ hp + factor(cyl), mtcars)
modelsummary(mod, statistic = 'conf.int', conf_level = .99)
modelplot(mod, statistic = 'conf.int', conf_level = .99)
```
This is especially problematic because `estimatr::tidy` accepts the ellipsis, which means we can pass `conf.level=.99` and it …

new tidy arguments: conf.int & conf.level

---

src/lm_robust_helper.cpp
tests/testthat/test-lm-robust-fes.R

The target for demeaning for fixed effects now scales with the scale of the covariate being demeaned, much like `lfe` does.
Closes #312

Fix fixed_effects failing to converge with large numbers

---

DESCRIPTION
NEWS.md

Update news and description (key change = require R 3.6 as 3.5 is no longer "old").

Prep for CRAN submission v0.24
